config/routes.rb
require 'sidekiq/web'
ClinicalVariantDatabase::Application.routes.draw do
  resources :uploads do
    get 'parse', :on => :member 
  end
  
  resources :parsers

  resources :chromosomes

  resources :variants do
  	
  	collection do
  		match 'search' => 'variants#index', :via => [:get, :post], :as => :search
  	end
    get 'query_biomart', :on => :member
    get 'query_provean', :on => :member

    get 'batch_query_biomart', :on => :collection
    get 'batch_query_provean', :on => :collection
    resources :locations
  end
  
  mount Sidekiq::Web, at: "/sidekiq"
  
  resources :quality_records

  resources :samples do
  	collection do
  		match 'search' => 'samples#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :genes do
  	collection do
  		match 'search' => 'genes#index', :via => [:get, :post], :as => :search
  	end
  	resources :locations
  end
  
  resources :disorders do
  	collection do
  		match 'search' => 'disorders#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :samples do
  	collection do
  		match 'search' => 'samples#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :protein_sequence_variants do
  	collection do
  		match 'search' => 'protein_sequence_variants#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :subjects do
  	collection do
  		match 'search' => 'subjects#index', :via => [:get, :post], :as => :search
  	end
  	get 'pedigree', :on => :member
  end
  
  
  root :to => 'uploads#index'

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  	
  attr_accessible :quality_record_id, :subject_id, :genotype, :total_read_depth, :conditional_genotype_quality, :genotype_likelihood, :allele_read_depth
  
  belongs_to :quality_record
  belongs_to :subject
  

end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # GET /samples
  # GET /samples.json
  def index

    if !params[:q]
      params[:q] = {:order => "descend_by_id"}	
    end
    
    @search = Sample.search(params[:q])   
    @samples = @search.result.page(params[:page]).per(20)
    @search.build_condition

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @sample = Sample.find(params[:id])
 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.json
  def new
    @sample = Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(params[:sample])

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render json: @sample, status: :created, location: @sample }
      else
        format.html { render action: "new" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.json
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end


  
end

app/views/samples/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:location] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/samples/_sample.html.erb
<table>
	<tr>
	  <th class="header" >
	  	<b>Name:</b>
	  </th>
		<th class="header" >
			<b>Genotype:</b>
  	</th>
  	<th class="header" >
			<b>Total read depth:</b>
  	</th>
  	<th class="header" >
			<b>Conditional genotype quality:</b>
  	</th>
  	<th class="header" >
			<b>Genotype likelihood:</b>
  	</th>
  	<th class="header" >
			<b>Allele read depth:</b>
  	</th>
  </tr>
  <tr>
    <td>
    	<%= sample.subject.name %>
    </td>
  	<td>
  		<%= sample.genotype %>
  	</td>
  	<td>
  		<%= sample.total_read_depth %>
  	</td>
  	<td>
  		<%= sample.conditional_genotype_quality %>
  	</td>
  	<td>
  		<%= sample.genotype_likelihood %>
  	</td>
  	<td>
  		<%= sample.allele_read_depth %>
  	</td>
  </tr>
</table>

app/views/samples/_sample_row.html.erb
  <tr>
    <td class="sample">
    	<%= sample_row.subject.name %>
    </td>
  	<td class="sample">
  		<%= sample_row.genotype %>
  	</td>
  	<td class="sample">
  		<%= sample_row.total_read_depth %>
  	</td>
  	<td class="sample">
  		<%= sample_row.conditional_genotype_quality  %>
  	</td>
  	<td class="sample">
  		<%= sample_row.genotype_likelihood %>
  	</td>
  	<td class="sample">
  		<%= sample_row.allele_read_depth %>
  	</td>
  </tr>

app/views/samples/_search_partial.html.erb
<%= search_form_for @search, url: search_samples_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
  <p><%= link_to_add_fields "Add Conditions", f, :condition %>
  <div class="actions"><%= f.submit "Search", class: 'btn btn-success' %></div>
<% end %>

app/views/samples/index.html.erb
<h1>Listing samples</h1>

<table>
  <tr>
    <th class="header" ><%= sort_link(@search, :id, "Id") %></th>
    <th class="header" ><%= sort_link(@search, :subject_name, "Name") %></th>
    <th class="header" ><%= sort_link(@search, :genotype, "GT") %></th>
    <th class="header" ><%= sort_link(@search, :total_read_depth, "DP") %></th>
    <th class="header" ><%= sort_link(@search, :conditional_genotype_quality, "GQ") %></th>
    <th class="header" ><%= sort_link(@search, :genotype_likelihood, "PL") %></th>
    <th class="header" ><%= sort_link(@search, :allele_read_depth, "AD") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @samples.each do |sample| %>
  <tr>
    <td><%= sample.id %></td>
    <td><%= sample.subject.name %></td>
    <td><%= sample.genotype %></td>
    <td><%= sample.total_read_depth %></td>
    <td><%= sample.conditional_genotype_quality %></td>
    <td><%= sample.genotype_likelihood %></td>
    <td><%= sample.allele_read_depth %></td>
    <td><%= button_to 'Show', sample, method: :get, class: 'btn btn-success' %></td>
    <td><%= button_to 'Edit', edit_sample_path(sample), method: :get, class: 'btn btn-warning' %></td>
    <td><%= button_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>
<%= paginate @samples %>
<%= render :partial => 'search_partial' %>
<%= link_to 'New Sample', new_sample_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Id:</b>
  <%= @sample.id %>
</p>
<p>
  <b>Subject name:</b>
  <%= @sample.subject.name %>
</p>
<p>
  <b>Genotype:</b>
  <%= @sample.genotype %>
</p>
<p>
  <b>Total read depth:</b>
  <%= @sample.total_read_depth %>
</p>
<p>
  <b>Conditional genotype quality:</b>
  <%= @sample.conditional_genotype_quality %>
</p>
<p>
  <b>Genotype likelihood:</b>
  <%= @sample.genotype_likelihood %>
</p>
<p>
  <b>Allele read depth:</b>
  <%= @sample.allele_read_depth %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>