config/routes.rb
require 'sidekiq/web'
ClinicalVariantDatabase::Application.routes.draw do
  resources :uploads do
    get 'parse', :on => :member 
  end
  
  resources :parsers

  resources :chromosomes

  resources :variants do
  	
  	collection do
  		match 'search' => 'variants#index', :via => [:get, :post], :as => :search
  	end
    get 'query_biomart', :on => :member
    get 'query_provean', :on => :member

    get 'batch_query_biomart', :on => :collection
    get 'batch_query_provean', :on => :collection
    resources :locations
  end
  
  mount Sidekiq::Web, at: "/sidekiq"
  
  resources :quality_records

  resources :samples do
  	collection do
  		match 'search' => 'samples#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :genes do
  	collection do
  		match 'search' => 'genes#index', :via => [:get, :post], :as => :search
  	end
  	resources :locations
  end
  
  resources :disorders do
  	collection do
  		match 'search' => 'disorders#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :samples do
  	collection do
  		match 'search' => 'samples#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :protein_sequence_variants do
  	collection do
  		match 'search' => 'protein_sequence_variants#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :subjects do
  	collection do
  		match 'search' => 'subjects#index', :via => [:get, :post], :as => :search
  	end
  	get 'pedigree', :on => :member
  end
  
  
  root :to => 'uploads#index'

end

app/models/disorder.rb
class Disorder < ActiveRecord::Base
  include Biomart
  attr_accessible :omim_id, :disorder_omim_id, :name, :disorder_type

  has_and_belongs_to_many :genes

  def query_biomart(gene_symbol)
    biomart = Biomart::Server.new("http://www.biomart.org/biomart")
    omim = biomart.datasets["omim"]
    
    response = omim.search(:filters => {"human_gene_symbol" => gene_symbol},
    	:attributes => ["omim_id", "disorder_omim_id", "disorder_name", "disorder_type", "human_gene_symbol"])

    return response
  end
  
  def build_disorder(response, gene_id)
    if response
      self.omim_id = response[:data][0][0]
      self.disorder_omim_id  = response[:data][0][1]
      self.name = response[:data][0][2]
      self.disorder_type = response[:data][0][3]
      
      this_gene = Gene.find(gene_id)
      self.genes.push(this_gene)
      self.save!
    end
  end
end

app/controllers/disorders_controller.rb
class DisordersController < ApplicationController
  # GET /disorders
  # GET /disorders.json
  def index

    if !params[:q]
      params[:q] = {:order => "descend_by_id"}	
    end
    
    @search = Disorder.search(params[:q])   
    @disorders = @search.result.page(params[:page]).per(20)
    @search.build_condition

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @disorders }
    end
  end

  # GET /disorders/1
  # GET /disorders/1.json
  def show
    @disorder = Disorder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @disorder }
    end
  end

  # GET /disorders/new
  # GET /disorders/new.json
  def new
    @disorder = Disorder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @disorder }
    end
  end

  # GET /disorders/1/edit
  def edit
    @disorder = Disorder.find(params[:id])
  end

  # POST /disorders
  # POST /disorders.json
  def create
    @disorder = Disorder.new(params[:disorder])

    respond_to do |format|
      if @disorder.save
        format.html { redirect_to @disorder, notice: 'Disorder was successfully created.' }
        format.json { render json: @disorder, status: :created, location: @disorder }
      else
        format.html { render action: "new" }
        format.json { render json: @disorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /disorders/1
  # PUT /disorders/1.json
  def update
    @disorder = Disorder.find(params[:id])

    respond_to do |format|
      if @disorder.update_attributes(params[:disorder])
        format.html { redirect_to @disorder, notice: 'Disorder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @disorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disorders/1
  # DELETE /disorders/1.json
  def destroy
    @disorder = Disorder.find(params[:id])
    @disorder.destroy

    respond_to do |format|
      format.html { redirect_to disorders_url }
      format.json { head :no_content }
    end
  end

end

app/views/disorders/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:location] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/disorders/_form.html.erb
<%= form_for(@disorder) do |f| %>
  <% if @disorder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disorder.errors.count, "error") %> prohibited this gene from being saved:</h2>

      <ul>
      <% @disorder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :omim_id %><br />
    <%= f.text_field :omim_id %>
  </div>
  <div class="field">
    <%= f.label :disorder_omim_id %><br />
    <%= f.text_field :disorder_omim_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :disorder_type %><br />
    <%= f.text_field :disorder_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disorders/_search_partial.html.erb
<%= search_form_for @search, url: search_disorders_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
  <p><%= link_to_add_fields "Add Conditions", f, :condition %>
  <div class="actions"><%= f.submit "Search", class: 'btn btn-success' %></div>
<% end %>

app/views/disorders/edit.html.erb
<h1>Editing disorder</h1>

<%= render 'form' %>

<%= link_to 'Show', @disorder %> |
<%= link_to 'Back', disorders_path %>

app/views/disorders/index.html.erb
<h1>Listing disorders</h1>
<%= button_to 'New Disorder', new_disorder_path, method: :get, class: 'btn btn-success' %>
<table>
  <tr>
    <th class="header" ><%= sort_link(@search, :id, "Id") %></th>
    <th class="header" ><%= sort_link(@search, :omim_id, "OMIM Id") %></th>
    <th class="header" ><%= sort_link(@search, :disorder_omim_id, "OMIM disorder Id") %></th>
    <th class="header" ><%= sort_link(@search, :name, "Disorder name") %></th>
    <th class="header" ><%= sort_link(@search, :disorder_type, "Disorder type") %></th>
    <th class="header" >Genes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disorders.each do |disorder| %>
  <tr>
    <td><%= disorder.id %></td>
    <td><%= link_to disorder.omim_id, "http://www.omim.org/entry/#{disorder.omim_id}" %></td>
    <td><%= disorder.disorder_omim_id %></td>
    <td><%= disorder.name %></td>
    <td><%= disorder.disorder_type %></td>
    <td>
    <% disorder.genes.each do |gene| %>
     <%= link_to gene.external_gene_id, gene_path(gene)  %>
    <% end %>
    </td>
    <td><%= button_to 'Show', disorder, method: :get, class: 'btn btn-success' %></td>
    <td><%= button_to 'Edit', edit_disorder_path(disorder), method: :get, class: 'btn btn-warning' %></td>
    <td><%= button_to 'Destroy', disorder, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>
<%= paginate @disorders %>
<%= render :partial => 'search_partial' %>

app/views/disorders/new.html.erb
<h1>New disorder</h1>

<%= render 'form' %>

<%= link_to 'Back', disorders_path %>

app/views/disorders/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Id:</b>
  <%= @disorder.id %>
</p>
<p>
  <b>OMIM Id:</b>
  <%= @disorder.omim_id %>
</p>
<p>
  <b>Disorder OMIM Id:</b>
  <%= @disorder.disorder_omim_id %>
</p>
<p>
  <b>Name:</b>
  <%= @disorder.name %>
</p>
<p>
  <b>Type:</b>
  <%= @disorder.disorder_type %>
</p>

<table>
<%= render :partial => 'genes/gene_row', :collection => @disorder.genes %>
</table>
<%= link_to 'Edit', edit_disorder_path(@disorder) %> |
<%= link_to 'Back', disorders_path %>