config/routes.rb
require 'sidekiq/web'
ClinicalVariantDatabase::Application.routes.draw do
  resources :uploads do
    get 'parse', :on => :member 
  end
  
  resources :parsers

  resources :chromosomes

  resources :variants do
  	
  	collection do
  		match 'search' => 'variants#index', :via => [:get, :post], :as => :search
  	end
    get 'query_biomart', :on => :member
    get 'query_provean', :on => :member

    get 'batch_query_biomart', :on => :collection
    get 'batch_query_provean', :on => :collection
    resources :locations
  end
  
  mount Sidekiq::Web, at: "/sidekiq"
  
  resources :quality_records

  resources :samples do
  	collection do
  		match 'search' => 'samples#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :genes do
  	collection do
  		match 'search' => 'genes#index', :via => [:get, :post], :as => :search
  	end
  	resources :locations
  end
  
  resources :disorders do
  	collection do
  		match 'search' => 'disorders#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :samples do
  	collection do
  		match 'search' => 'samples#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :protein_sequence_variants do
  	collection do
  		match 'search' => 'protein_sequence_variants#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :subjects do
  	collection do
  		match 'search' => 'subjects#index', :via => [:get, :post], :as => :search
  	end
  	get 'pedigree', :on => :member
  end
  
  
  root :to => 'uploads#index'

end

app/models/subject.rb
class Subject < ActiveRecord::Base

  attr_accessible :name
  
  has_many :samples 
  has_many :quality_records, :through => :samples
  has_many :variants, :through => :quality_records
  
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  def index

    if !params[:q]
      params[:q] = {:order => "descend_by_id"}	
    end
    
    @search = Subject.search(params[:q])   
    @subjects = @search.result.page(params[:page]).per(20)
    @search.build_condition

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  	
    @subject = Subject.find(params[:id])
    @variants = @subject.variants.page(params[:page]).per(10)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end
  
  def pedigree
  	@subject = Subject.find(params[:id])
  	
  	respond_to do |format|
      format.html # pedigree.html.erb
      format.json { render json: @subject }
    end
  end


  
end

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <tr>
    <th class="header" ><%= sort_link(@search, :id, "Id") %></th>
    <th class="header" ><%= sort_link(@search, :name, "Name") %></th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.id %></td>
    <td><%= subject.name %></td>
    <td><%= button_to 'Show', subject, method: :get, class: 'btn btn-success' %></td>
    <td><%= button_to 'Edit', edit_subject_path(subject), method: :get, class: 'btn btn-warning' %></td>
    <td><%= button_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>
<%= paginate @subjects %>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/pedigree.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<style>

text {
  font-family: "Helvetica Neue", Helvetica, sans-serif;
}

.name {
  font-weight: bold;
}

.about {
  fill: #777;
  font-size: smaller;
}

.link {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

</style>
<body>
<script src="http://d3js.org/d3.v2.min.js?2.9.4"></script>
<script>

var margin = {top: 0, right: 320, bottom: 0, left: 0},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var tree = d3.layout.tree()
    .separation(function(a, b) { return a.parent === b.parent ? 1 : .5; })
    .children(function(d) { return d.parents; })
    .size([height, width]);

var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

d3.json("pedigree.json", function(json) {
  var nodes = tree.nodes(json);

  var link = svg.selectAll(".link")
      .data(tree.links(nodes))
    .enter().append("path")
      .attr("class", "link")
      .attr("d", elbow);

  var node = svg.selectAll(".node")
      .data(nodes)
    .enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; })

  node.append("text")
      .attr("class", "name")
      .attr("x", 8)
      .attr("y", -6)
      .text(function(d) { return d.name; });

  node.append("text")
      .attr("x", 8)
      .attr("y", 8)
      .attr("dy", ".71em")
      .attr("class", "about lifespan")
      .text(function(d) { return d.born + "–" + d.died; });

  node.append("text")
      .attr("x", 8)
      .attr("y", 8)
      .attr("dy", "1.86em")
      .attr("class", "about location")
      .text(function(d) { return d.location; });
});

function elbow(d, i) {
  return "M" + d.source.y + "," + d.source.x
       + "H" + d.target.y + "V" + d.target.x
       + (d.target.children ? "" : "h" + margin.right);
}

</script>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Id:</b>
  <%= @subject.id %>
</p>
<p>
  <b>name:</b>
  <%= @subject.name %>
</p>
<table>
<%= render :partial => 'variants/variant_row', :collection => @variants %>
</table>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>