config/routes.rb
require 'sidekiq/web'
ClinicalVariantDatabase::Application.routes.draw do
  resources :uploads do
    get 'parse', :on => :member 
  end
  
  resources :parsers

  resources :chromosomes

  resources :variants do
  	
  	collection do
  		match 'search' => 'variants#index', :via => [:get, :post], :as => :search
  	end
    get 'query_biomart', :on => :member
    get 'query_provean', :on => :member

    get 'batch_query_biomart', :on => :collection
    get 'batch_query_provean', :on => :collection
    resources :locations
  end
  
  mount Sidekiq::Web, at: "/sidekiq"
  
  resources :quality_records

  resources :samples do
  	collection do
  		match 'search' => 'samples#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :genes do
  	collection do
  		match 'search' => 'genes#index', :via => [:get, :post], :as => :search
  	end
  	resources :locations
  end
  
  resources :disorders do
  	collection do
  		match 'search' => 'disorders#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :samples do
  	collection do
  		match 'search' => 'samples#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :protein_sequence_variants do
  	collection do
  		match 'search' => 'protein_sequence_variants#index', :via => [:get, :post], :as => :search
  	end
  end
  
  resources :subjects do
  	collection do
  		match 'search' => 'subjects#index', :via => [:get, :post], :as => :search
  	end
  	get 'pedigree', :on => :member
  end
  
  
  root :to => 'uploads#index'

end

app/models/gene.rb
class Gene < ActiveRecord::Base
  include Biomart
  attr_accessible :external_gene_id, :ensembl_gene_id, :hgnc_id, :transcript_count
  
  has_many :locations, :as => :locatable
  has_and_belongs_to_many :disorders
  
  before_destroy :delete_disorders
  before_destroy :delete_locatable
  
  def find_variants
  	variants = Array.new
  	locations = Location.includes_variant_location(self.locations.first.position_start, self.locations.first.position_end)
  	locations.each do |location|
  		variants.push( location.locatable )
  	end
  	return variants
  end
  
  def convert_strand_string(strand)
  	  if strand == "-1"
  	    return "-"
  	  elsif strand == "1"
  	    return "+"
  	  end
  end
  
  def query_biomart(chromosome_name, start_position)
    biomart = Biomart::Server.new("http://www.biomart.org/biomart")
    ensembl = biomart.datasets["hsapiens_gene_ensembl"]
    
    response = ensembl.search(:filters => {"chromosome_name" => chromosome_name, "start" => start_position.to_i, "end" => start_position.to_i+1, "status" => "KNOWN"},
    	:attributes => ["external_gene_id", "ensembl_gene_id", "hgnc_id","chromosome_name", "strand", "start_position", "end_position", "transcript_count"])
    return response
  end
  
  def build_gene(response)
    if ((response) && !(Gene.find_by_ensembl_gene_id(response[:data][0][1])))
      self.external_gene_id = response[:data][0][0]
      self.ensembl_gene_id  = response[:data][0][1]
      self.hgnc_id					= response[:data][0][2]
      self.transcript_count = response[:data][0][7]
      
      this_chromosome = Chromosome.find_by_name(response[:data][0][3])
      
      this_location = Location.new
      this_location.strand	     = convert_strand_string(response[:data][0][4])
      this_location.position_start   = response[:data][0][5]
      this_location.position_end     = response[:data][0][6]
      this_location.chromosome = this_chromosome
      
      self.locations.push(this_location)
      if !(Gene.find_by_ensembl_gene_id(self.ensembl_gene_id))
      	self.save!
      	self.reload
      	this_disorder = Disorder.new
        disorder_response = this_disorder.query_biomart(self.external_gene_id)
        if ((disorder_response) && !(Disorder.find_by_omim_id(response[:data][0][0])))
      	  this_disorder.build_disorder(disorder_response, self.id)
        end
        self.save!
      end

    end
  end
  
  def self.remove_duplicates 
    grouped = all.group_by{|model| [model.ensembl_gene_id] }
    grouped.values.each do |duplicates|
      first_one = duplicates.shift 
      duplicates.each{|leftover| leftover.destroy} 
    end
  end

  protected
  
  def delete_locatable
  	if self.locations.length > 0
  		self.locations.delete_all
  	end
  end
  
  def delete_disorders
  	if self.disorders.length > 0
  		self.disorders.delete_all
  	end
  end
  
end

app/controllers/genes_controller.rb
class GenesController < ApplicationController
  # GET /genes
  # GET /genes.json
  def index
    
    @search = Gene.search(params[:q])   
    @genes = @search.result.page(params[:page]).per(20)
    @search.build_condition

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genes }
    end
  end

  # GET /genes/1
  # GET /genes/1.json
  def show
    @gene = Gene.find(params[:id])
    @variants = @gene.find_variants
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gene }
    end
  end

  # GET /genes/new
  # GET /genes/new.json
  def new
    @gene = Gene.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gene }
    end
  end

  # GET /genes/1/edit
  def edit
    @gene = Gene.find(params[:id])
  end

  # POST /genes
  # POST /genes.json
  def create
    @gene = Gene.new(params[:gene])

    respond_to do |format|
      if @gene.save
        format.html { redirect_to @gene, notice: 'Gene was successfully created.' }
        format.json { render json: @gene, status: :created, location: @gene }
      else
        format.html { render action: "new" }
        format.json { render json: @gene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genes/1
  # PUT /genes/1.json
  def update
    @gene = Gene.find(params[:id])

    respond_to do |format|
      if @gene.update_attributes(params[:gene])
        format.html { redirect_to @gene, notice: 'Gene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genes/1
  # DELETE /genes/1.json
  def destroy
    @gene = Gene.find(params[:id])
    @gene.destroy

    respond_to do |format|
      format.html { redirect_to genes_url }
      format.json { head :no_content }
    end
  end

  def query_biomart
    @variants = Variant.all  
    @variants.each do |variant|
      if variant.location.position_start
      	if !((location = Location.includes_location(variant.location.position_start).first ) && ( location.gene?)) 
      	      this_gene = Gene.new
      	      this_response = this_gene.query_biomart(variant.location.chromosome.name, variant.location.position_start)
      	      this_gene.build_gene(this_response)
        end
      end
    end
    respond_to do |format|
      format.html 
      format.json { render json: @genes }
    end
  end
 
end

app/views/genes/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:location] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/genes/_form.html.erb
<%= form_for(@gene) do |f| %>
  <% if @gene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gene.errors.count, "error") %> prohibited this gene from being saved:</h2>

      <ul>
      <% @gene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :external_gene_id %><br />
    <%= f.text_field :external_gene_id %>
  </div>
  <div class="field">
    <%= f.label :ensembl_gene_id %><br />
    <%= f.text_field :ensembl_gene_id %>
  </div>
  <div class="field">
    <%= f.label :transcript_count %><br />
    <%= f.text_field :transcript_count %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genes/_gene.html.erb
<table>
	<tr>
	  <th class="header gene" >
	  	Gene id:
	  </th>
		<th class="header gene" >
			External Gene Id:
  	</th>
  	<th class="header gene" >
			Ensembl Gene Id:
  	</th>
  	<th class="header gene" >
		  Transcript Count:
  	</th>
  </tr>
  <tr>
    <td>
      <%= link_to gene.id, gene_path(gene)  %>
    </td>
  	<td>
  		<%= gene.external_gene_id %>
  	</td>
  	<td>
  		<%= gene.ensembl_gene_id %>
  	</td>
  	<td>
  		<%= gene.transcript_count %>
  	</td>
  </tr>
</table> 

app/views/genes/_gene_row.html.erb
	<tr>
	  <th class="header gene" >
	  	Gene id:
	  </th>
		<th class="header gene" >
			External Gene Id:
  	</th>
  	<th class="header gene" >
			Ensembl Gene Id:
  	</th>
  	<th class="header gene" >
		  Transcript Count:
  	</th>
  </tr>
  <tr>
    <td>
      <%= link_to gene_row.id, gene_path(gene_row)  %>
    </td>
  	<td>
  		<%= gene_row.external_gene_id %>
  	</td>
  	<td>
  		<%= gene_row.ensembl_gene_id %>
  	</td>
  	<td>
  		<%= gene_row.transcript_count %>
  	</td>
  </tr>
  

app/views/genes/_search_partial.html.erb
<%= search_form_for @search, url: search_genes_path, method: :post do |f| %>
  <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>
  <p><%= link_to_add_fields "Add Conditions", f, :condition %>
  <div class="actions"><%= f.submit "Search", class: 'btn btn-success' %></div>
<% end %>

app/views/genes/edit.html.erb
<h1>Editing gene</h1>

<%= render 'form' %>

<%= link_to 'Show', @gene %> |
<%= link_to 'Back', genes_path %>

app/views/genes/index.html.erb
<h1>Listing genes</h1>
<%= button_to 'New Gene', new_gene_path, method: :get, class: 'btn btn-success' %>
<table>
  <tr>
    <th class="header" ><%= sort_link(@search, :id, "Id") %></th>
    <th class="header" ><%= sort_link(@search, :external_gene_id, "External Gene Id") %></th>
    <th class="header" ><%= sort_link(@search, :ensembl_gene_id, "Ensembl Gene Id") %></th>
    <th class="header" ><%= sort_link(@search, :transcript_count, "Transcript Count") %></th>
    <th class="header" >CATH-Gene3D</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @genes.each do |gene| %>
  <tr>
    <td><%= gene.id %></td>
    <td><%= gene.external_gene_id %></td>
    <td><%= link_to gene.ensembl_gene_id, "http://www.ensembl.org/Homo_sapiens/Location/View?db=core;g=#{gene.ensembl_gene_id}" %></td>
    <td><%= gene.transcript_count %></td>
    <td><%= button_to "CATH-Gene3D", "http://gene3d.biochem.ucl.ac.uk/Gene3D/proteins/?keywords=#{gene.ensembl_gene_id}&taxon-filter=HOMO+SAPIENS+%28taxon_ID%3A9606%29%2C+&fastas=", class: 'btn btn-inverse' %></td>
    <td><%= button_to 'Show', gene, method: :get, class: 'btn btn-success' %></td>
    <td><%= button_to 'Edit', edit_gene_path(gene), method: :get, class: 'btn btn-warning' %></td>
    <td><%= button_to 'Destroy', gene, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>
<%= paginate @genes %>
<%= render :partial => 'search_partial' %>

app/views/genes/new.html.erb
<h1>New gene</h1>

<%= render 'form' %>

<%= link_to 'Back', genes_path %>

app/views/genes/show.html.erb
<p id="notice"><%= notice %></p>
<table>
<%= render :partial => 'genes/gene_row', locals: {gene_row: @gene} %>
</table>
<table>
<%= render :partial => 'variants/variant_row', :collection => @variants %>
</table>

<%= link_to 'Edit', edit_gene_path(@gene) %> |
<%= link_to 'Back', genes_path %>